development:
  host: localhost
  database: startup_weekend_development

test:
  host: localhost
  database: startup_weekend_test

# set these environment variables on your prod server
# MONGOHQ_URL configured when mongoid add on added 
production: 
  uri: <%= ENV['MONGOHQ_URL'] %>